apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: web
          image: ghcr.io/kubernetes-up-and-running/guestbook:v1
          ports:
            - containerPort: 3000
